version: "3.3"
services:
  app: 
    image: mcr.microsoft.com/devcontainers/typescript-node:20-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    extra_hosts: 
      - "host.docker.internal:host-gateway"
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Newpassword
    ports:
      - '5432:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: